#!/bin/bash

HERE=$PWD

echo "Running all unit tests ..."
nosetests -w ../src || exit 1
echo "Unit tests passed"
echo
echo "Running system tests using in-memory db ..."

python ../src/poemtube-dev-memory.py &
sleep 1

nosetests
RETVAL=$?

kill %1

if [ "$RETVAL" != "0" ]; then exit $RETVAL; fi

echo "In-memory tests passed."
echo
echo "Running system tests using real couchdb ..."

python ../src/setup/install.py --prefix=systest- --delete || exit 1
python ../src/poemtube-systest.py &
sleep 1

cd $HERE
nosetests

RETVAL=$?
kill %1

if [ "$RETVAL" != "0" ]; then exit $RETVAL; fi

echo "Couchdb tests passed."
echo
echo "All tests passed."

