#!/bin/bash

HERE=$PWD

echo "Running system tests using in-memory db ..."

TMPFILE=`mktemp -d` || exit 1
cd $TMPFILE || exit 1
python $HERE/../src/poemtube-dev.py &

cd $HERE
nosetests

RETVAL=$?
kill %1
rm -rf $TMPFILE

if [ "$RETVAL" != "0" ]; then exit $RETVAL; fi

echo "In-memory tests passed."
echo
echo "Running system tests using real couchdb ..."

TMPFILE=`mktemp -d` || exit 1
cd $TMPFILE || exit 1
echo '{"db": "couch", "prefix": "systest-"}' > config.json
python $HERE/../src/setup/install.py --prefix=systest- --delete || exit 1
python $HERE/../src/poemtube-dev.py &

cd $HERE
nosetests

RETVAL=$?
kill %1
rm -rf $TMPFILE

if [ "$RETVAL" != "0" ]; then exit $RETVAL; fi

echo "Couchdb tests passed."
echo
echo "All tests passed."

